
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `item` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model item
 * 
 */
export type itemModel = runtime.Types.Result.DefaultSelection<Prisma.$itemPayload>

export type AggregateItem = {
  _count: ItemCountAggregateOutputType | null
  _min: ItemMinAggregateOutputType | null
  _max: ItemMaxAggregateOutputType | null
}

export type ItemMinAggregateOutputType = {
  id: string | null
  menuId: string | null
  platfrom: $Enums.platfrom | null
  arch: $Enums.arch | null
  target: string | null
  updated_at: Date | null
}

export type ItemMaxAggregateOutputType = {
  id: string | null
  menuId: string | null
  platfrom: $Enums.platfrom | null
  arch: $Enums.arch | null
  target: string | null
  updated_at: Date | null
}

export type ItemCountAggregateOutputType = {
  id: number
  menuId: number
  platfrom: number
  arch: number
  target: number
  updated_at: number
  _all: number
}


export type ItemMinAggregateInputType = {
  id?: true
  menuId?: true
  platfrom?: true
  arch?: true
  target?: true
  updated_at?: true
}

export type ItemMaxAggregateInputType = {
  id?: true
  menuId?: true
  platfrom?: true
  arch?: true
  target?: true
  updated_at?: true
}

export type ItemCountAggregateInputType = {
  id?: true
  menuId?: true
  platfrom?: true
  arch?: true
  target?: true
  updated_at?: true
  _all?: true
}

export type ItemAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which item to aggregate.
   */
  where?: Prisma.itemWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of items to fetch.
   */
  orderBy?: Prisma.itemOrderByWithRelationInput | Prisma.itemOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.itemWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` items from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` items.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned items
  **/
  _count?: true | ItemCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: ItemMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: ItemMaxAggregateInputType
}

export type GetItemAggregateType<T extends ItemAggregateArgs> = {
      [P in keyof T & keyof AggregateItem]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateItem[P]>
    : Prisma.GetScalarType<T[P], AggregateItem[P]>
}




export type itemGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.itemWhereInput
  orderBy?: Prisma.itemOrderByWithAggregationInput | Prisma.itemOrderByWithAggregationInput[]
  by: Prisma.ItemScalarFieldEnum[] | Prisma.ItemScalarFieldEnum
  having?: Prisma.itemScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: ItemCountAggregateInputType | true
  _min?: ItemMinAggregateInputType
  _max?: ItemMaxAggregateInputType
}

export type ItemGroupByOutputType = {
  id: string
  menuId: string
  platfrom: $Enums.platfrom
  arch: $Enums.arch
  target: string
  updated_at: Date
  _count: ItemCountAggregateOutputType | null
  _min: ItemMinAggregateOutputType | null
  _max: ItemMaxAggregateOutputType | null
}

export type GetItemGroupByPayload<T extends itemGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<ItemGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof ItemGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], ItemGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], ItemGroupByOutputType[P]>
      }
    >
  >



export type itemWhereInput = {
  AND?: Prisma.itemWhereInput | Prisma.itemWhereInput[]
  OR?: Prisma.itemWhereInput[]
  NOT?: Prisma.itemWhereInput | Prisma.itemWhereInput[]
  id?: Prisma.StringFilter<"item"> | string
  menuId?: Prisma.StringFilter<"item"> | string
  platfrom?: Prisma.EnumplatfromFilter<"item"> | $Enums.platfrom
  arch?: Prisma.EnumarchFilter<"item"> | $Enums.arch
  target?: Prisma.StringFilter<"item"> | string
  updated_at?: Prisma.DateTimeFilter<"item"> | Date | string
  menu?: Prisma.XOR<Prisma.MenuScalarRelationFilter, Prisma.menuWhereInput>
}

export type itemOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  menuId?: Prisma.SortOrder
  platfrom?: Prisma.SortOrder
  arch?: Prisma.SortOrder
  target?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
  menu?: Prisma.menuOrderByWithRelationInput
}

export type itemWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  menuId_platfrom_arch?: Prisma.itemMenuIdPlatfromArchCompoundUniqueInput
  AND?: Prisma.itemWhereInput | Prisma.itemWhereInput[]
  OR?: Prisma.itemWhereInput[]
  NOT?: Prisma.itemWhereInput | Prisma.itemWhereInput[]
  menuId?: Prisma.StringFilter<"item"> | string
  platfrom?: Prisma.EnumplatfromFilter<"item"> | $Enums.platfrom
  arch?: Prisma.EnumarchFilter<"item"> | $Enums.arch
  target?: Prisma.StringFilter<"item"> | string
  updated_at?: Prisma.DateTimeFilter<"item"> | Date | string
  menu?: Prisma.XOR<Prisma.MenuScalarRelationFilter, Prisma.menuWhereInput>
}, "id" | "menuId_platfrom_arch">

export type itemOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  menuId?: Prisma.SortOrder
  platfrom?: Prisma.SortOrder
  arch?: Prisma.SortOrder
  target?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
  _count?: Prisma.itemCountOrderByAggregateInput
  _max?: Prisma.itemMaxOrderByAggregateInput
  _min?: Prisma.itemMinOrderByAggregateInput
}

export type itemScalarWhereWithAggregatesInput = {
  AND?: Prisma.itemScalarWhereWithAggregatesInput | Prisma.itemScalarWhereWithAggregatesInput[]
  OR?: Prisma.itemScalarWhereWithAggregatesInput[]
  NOT?: Prisma.itemScalarWhereWithAggregatesInput | Prisma.itemScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"item"> | string
  menuId?: Prisma.StringWithAggregatesFilter<"item"> | string
  platfrom?: Prisma.EnumplatfromWithAggregatesFilter<"item"> | $Enums.platfrom
  arch?: Prisma.EnumarchWithAggregatesFilter<"item"> | $Enums.arch
  target?: Prisma.StringWithAggregatesFilter<"item"> | string
  updated_at?: Prisma.DateTimeWithAggregatesFilter<"item"> | Date | string
}

export type itemCreateInput = {
  id?: string
  platfrom: $Enums.platfrom
  arch: $Enums.arch
  target: string
  updated_at: Date | string
  menu: Prisma.menuCreateNestedOneWithoutItemsInput
}

export type itemUncheckedCreateInput = {
  id?: string
  menuId: string
  platfrom: $Enums.platfrom
  arch: $Enums.arch
  target: string
  updated_at: Date | string
}

export type itemUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  platfrom?: Prisma.EnumplatfromFieldUpdateOperationsInput | $Enums.platfrom
  arch?: Prisma.EnumarchFieldUpdateOperationsInput | $Enums.arch
  target?: Prisma.StringFieldUpdateOperationsInput | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  menu?: Prisma.menuUpdateOneRequiredWithoutItemsNestedInput
}

export type itemUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  menuId?: Prisma.StringFieldUpdateOperationsInput | string
  platfrom?: Prisma.EnumplatfromFieldUpdateOperationsInput | $Enums.platfrom
  arch?: Prisma.EnumarchFieldUpdateOperationsInput | $Enums.arch
  target?: Prisma.StringFieldUpdateOperationsInput | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type itemCreateManyInput = {
  id?: string
  menuId: string
  platfrom: $Enums.platfrom
  arch: $Enums.arch
  target: string
  updated_at: Date | string
}

export type itemUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  platfrom?: Prisma.EnumplatfromFieldUpdateOperationsInput | $Enums.platfrom
  arch?: Prisma.EnumarchFieldUpdateOperationsInput | $Enums.arch
  target?: Prisma.StringFieldUpdateOperationsInput | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type itemUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  menuId?: Prisma.StringFieldUpdateOperationsInput | string
  platfrom?: Prisma.EnumplatfromFieldUpdateOperationsInput | $Enums.platfrom
  arch?: Prisma.EnumarchFieldUpdateOperationsInput | $Enums.arch
  target?: Prisma.StringFieldUpdateOperationsInput | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ItemListRelationFilter = {
  every?: Prisma.itemWhereInput
  some?: Prisma.itemWhereInput
  none?: Prisma.itemWhereInput
}

export type itemOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type itemMenuIdPlatfromArchCompoundUniqueInput = {
  menuId: string
  platfrom: $Enums.platfrom
  arch: $Enums.arch
}

export type itemCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  menuId?: Prisma.SortOrder
  platfrom?: Prisma.SortOrder
  arch?: Prisma.SortOrder
  target?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
}

export type itemMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  menuId?: Prisma.SortOrder
  platfrom?: Prisma.SortOrder
  arch?: Prisma.SortOrder
  target?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
}

export type itemMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  menuId?: Prisma.SortOrder
  platfrom?: Prisma.SortOrder
  arch?: Prisma.SortOrder
  target?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
}

export type itemCreateNestedManyWithoutMenuInput = {
  create?: Prisma.XOR<Prisma.itemCreateWithoutMenuInput, Prisma.itemUncheckedCreateWithoutMenuInput> | Prisma.itemCreateWithoutMenuInput[] | Prisma.itemUncheckedCreateWithoutMenuInput[]
  connectOrCreate?: Prisma.itemCreateOrConnectWithoutMenuInput | Prisma.itemCreateOrConnectWithoutMenuInput[]
  createMany?: Prisma.itemCreateManyMenuInputEnvelope
  connect?: Prisma.itemWhereUniqueInput | Prisma.itemWhereUniqueInput[]
}

export type itemUncheckedCreateNestedManyWithoutMenuInput = {
  create?: Prisma.XOR<Prisma.itemCreateWithoutMenuInput, Prisma.itemUncheckedCreateWithoutMenuInput> | Prisma.itemCreateWithoutMenuInput[] | Prisma.itemUncheckedCreateWithoutMenuInput[]
  connectOrCreate?: Prisma.itemCreateOrConnectWithoutMenuInput | Prisma.itemCreateOrConnectWithoutMenuInput[]
  createMany?: Prisma.itemCreateManyMenuInputEnvelope
  connect?: Prisma.itemWhereUniqueInput | Prisma.itemWhereUniqueInput[]
}

export type itemUpdateManyWithoutMenuNestedInput = {
  create?: Prisma.XOR<Prisma.itemCreateWithoutMenuInput, Prisma.itemUncheckedCreateWithoutMenuInput> | Prisma.itemCreateWithoutMenuInput[] | Prisma.itemUncheckedCreateWithoutMenuInput[]
  connectOrCreate?: Prisma.itemCreateOrConnectWithoutMenuInput | Prisma.itemCreateOrConnectWithoutMenuInput[]
  upsert?: Prisma.itemUpsertWithWhereUniqueWithoutMenuInput | Prisma.itemUpsertWithWhereUniqueWithoutMenuInput[]
  createMany?: Prisma.itemCreateManyMenuInputEnvelope
  set?: Prisma.itemWhereUniqueInput | Prisma.itemWhereUniqueInput[]
  disconnect?: Prisma.itemWhereUniqueInput | Prisma.itemWhereUniqueInput[]
  delete?: Prisma.itemWhereUniqueInput | Prisma.itemWhereUniqueInput[]
  connect?: Prisma.itemWhereUniqueInput | Prisma.itemWhereUniqueInput[]
  update?: Prisma.itemUpdateWithWhereUniqueWithoutMenuInput | Prisma.itemUpdateWithWhereUniqueWithoutMenuInput[]
  updateMany?: Prisma.itemUpdateManyWithWhereWithoutMenuInput | Prisma.itemUpdateManyWithWhereWithoutMenuInput[]
  deleteMany?: Prisma.itemScalarWhereInput | Prisma.itemScalarWhereInput[]
}

export type itemUncheckedUpdateManyWithoutMenuNestedInput = {
  create?: Prisma.XOR<Prisma.itemCreateWithoutMenuInput, Prisma.itemUncheckedCreateWithoutMenuInput> | Prisma.itemCreateWithoutMenuInput[] | Prisma.itemUncheckedCreateWithoutMenuInput[]
  connectOrCreate?: Prisma.itemCreateOrConnectWithoutMenuInput | Prisma.itemCreateOrConnectWithoutMenuInput[]
  upsert?: Prisma.itemUpsertWithWhereUniqueWithoutMenuInput | Prisma.itemUpsertWithWhereUniqueWithoutMenuInput[]
  createMany?: Prisma.itemCreateManyMenuInputEnvelope
  set?: Prisma.itemWhereUniqueInput | Prisma.itemWhereUniqueInput[]
  disconnect?: Prisma.itemWhereUniqueInput | Prisma.itemWhereUniqueInput[]
  delete?: Prisma.itemWhereUniqueInput | Prisma.itemWhereUniqueInput[]
  connect?: Prisma.itemWhereUniqueInput | Prisma.itemWhereUniqueInput[]
  update?: Prisma.itemUpdateWithWhereUniqueWithoutMenuInput | Prisma.itemUpdateWithWhereUniqueWithoutMenuInput[]
  updateMany?: Prisma.itemUpdateManyWithWhereWithoutMenuInput | Prisma.itemUpdateManyWithWhereWithoutMenuInput[]
  deleteMany?: Prisma.itemScalarWhereInput | Prisma.itemScalarWhereInput[]
}

export type EnumplatfromFieldUpdateOperationsInput = {
  set?: $Enums.platfrom
}

export type EnumarchFieldUpdateOperationsInput = {
  set?: $Enums.arch
}

export type DateTimeFieldUpdateOperationsInput = {
  set?: Date | string
}

export type itemCreateWithoutMenuInput = {
  id?: string
  platfrom: $Enums.platfrom
  arch: $Enums.arch
  target: string
  updated_at: Date | string
}

export type itemUncheckedCreateWithoutMenuInput = {
  id?: string
  platfrom: $Enums.platfrom
  arch: $Enums.arch
  target: string
  updated_at: Date | string
}

export type itemCreateOrConnectWithoutMenuInput = {
  where: Prisma.itemWhereUniqueInput
  create: Prisma.XOR<Prisma.itemCreateWithoutMenuInput, Prisma.itemUncheckedCreateWithoutMenuInput>
}

export type itemCreateManyMenuInputEnvelope = {
  data: Prisma.itemCreateManyMenuInput | Prisma.itemCreateManyMenuInput[]
}

export type itemUpsertWithWhereUniqueWithoutMenuInput = {
  where: Prisma.itemWhereUniqueInput
  update: Prisma.XOR<Prisma.itemUpdateWithoutMenuInput, Prisma.itemUncheckedUpdateWithoutMenuInput>
  create: Prisma.XOR<Prisma.itemCreateWithoutMenuInput, Prisma.itemUncheckedCreateWithoutMenuInput>
}

export type itemUpdateWithWhereUniqueWithoutMenuInput = {
  where: Prisma.itemWhereUniqueInput
  data: Prisma.XOR<Prisma.itemUpdateWithoutMenuInput, Prisma.itemUncheckedUpdateWithoutMenuInput>
}

export type itemUpdateManyWithWhereWithoutMenuInput = {
  where: Prisma.itemScalarWhereInput
  data: Prisma.XOR<Prisma.itemUpdateManyMutationInput, Prisma.itemUncheckedUpdateManyWithoutMenuInput>
}

export type itemScalarWhereInput = {
  AND?: Prisma.itemScalarWhereInput | Prisma.itemScalarWhereInput[]
  OR?: Prisma.itemScalarWhereInput[]
  NOT?: Prisma.itemScalarWhereInput | Prisma.itemScalarWhereInput[]
  id?: Prisma.StringFilter<"item"> | string
  menuId?: Prisma.StringFilter<"item"> | string
  platfrom?: Prisma.EnumplatfromFilter<"item"> | $Enums.platfrom
  arch?: Prisma.EnumarchFilter<"item"> | $Enums.arch
  target?: Prisma.StringFilter<"item"> | string
  updated_at?: Prisma.DateTimeFilter<"item"> | Date | string
}

export type itemCreateManyMenuInput = {
  id?: string
  platfrom: $Enums.platfrom
  arch: $Enums.arch
  target: string
  updated_at: Date | string
}

export type itemUpdateWithoutMenuInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  platfrom?: Prisma.EnumplatfromFieldUpdateOperationsInput | $Enums.platfrom
  arch?: Prisma.EnumarchFieldUpdateOperationsInput | $Enums.arch
  target?: Prisma.StringFieldUpdateOperationsInput | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type itemUncheckedUpdateWithoutMenuInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  platfrom?: Prisma.EnumplatfromFieldUpdateOperationsInput | $Enums.platfrom
  arch?: Prisma.EnumarchFieldUpdateOperationsInput | $Enums.arch
  target?: Prisma.StringFieldUpdateOperationsInput | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type itemUncheckedUpdateManyWithoutMenuInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  platfrom?: Prisma.EnumplatfromFieldUpdateOperationsInput | $Enums.platfrom
  arch?: Prisma.EnumarchFieldUpdateOperationsInput | $Enums.arch
  target?: Prisma.StringFieldUpdateOperationsInput | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type itemSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  menuId?: boolean
  platfrom?: boolean
  arch?: boolean
  target?: boolean
  updated_at?: boolean
  menu?: boolean | Prisma.menuDefaultArgs<ExtArgs>
}, ExtArgs["result"]["item"]>

export type itemSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  menuId?: boolean
  platfrom?: boolean
  arch?: boolean
  target?: boolean
  updated_at?: boolean
  menu?: boolean | Prisma.menuDefaultArgs<ExtArgs>
}, ExtArgs["result"]["item"]>

export type itemSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  menuId?: boolean
  platfrom?: boolean
  arch?: boolean
  target?: boolean
  updated_at?: boolean
  menu?: boolean | Prisma.menuDefaultArgs<ExtArgs>
}, ExtArgs["result"]["item"]>

export type itemSelectScalar = {
  id?: boolean
  menuId?: boolean
  platfrom?: boolean
  arch?: boolean
  target?: boolean
  updated_at?: boolean
}

export type itemOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "menuId" | "platfrom" | "arch" | "target" | "updated_at", ExtArgs["result"]["item"]>
export type itemInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  menu?: boolean | Prisma.menuDefaultArgs<ExtArgs>
}
export type itemIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  menu?: boolean | Prisma.menuDefaultArgs<ExtArgs>
}
export type itemIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  menu?: boolean | Prisma.menuDefaultArgs<ExtArgs>
}

export type $itemPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "item"
  objects: {
    menu: Prisma.$menuPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    menuId: string
    platfrom: $Enums.platfrom
    arch: $Enums.arch
    target: string
    updated_at: Date
  }, ExtArgs["result"]["item"]>
  composites: {}
}

export type itemGetPayload<S extends boolean | null | undefined | itemDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$itemPayload, S>

export type itemCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<itemFindManyArgs, 'select' | 'include' | 'distinct' | 'omit' | 'relationLoadStrategy'> & {
    select?: ItemCountAggregateInputType | true
  }

export interface itemDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['item'], meta: { name: 'item' } }
  /**
   * Find zero or one Item that matches the filter.
   * @param {itemFindUniqueArgs} args - Arguments to find a Item
   * @example
   * // Get one Item
   * const item = await prisma.item.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends itemFindUniqueArgs>(args: Prisma.SelectSubset<T, itemFindUniqueArgs<ExtArgs>>): Prisma.Prisma__itemClient<runtime.Types.Result.GetResult<Prisma.$itemPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Item that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {itemFindUniqueOrThrowArgs} args - Arguments to find a Item
   * @example
   * // Get one Item
   * const item = await prisma.item.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends itemFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, itemFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__itemClient<runtime.Types.Result.GetResult<Prisma.$itemPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Item that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {itemFindFirstArgs} args - Arguments to find a Item
   * @example
   * // Get one Item
   * const item = await prisma.item.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends itemFindFirstArgs>(args?: Prisma.SelectSubset<T, itemFindFirstArgs<ExtArgs>>): Prisma.Prisma__itemClient<runtime.Types.Result.GetResult<Prisma.$itemPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Item that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {itemFindFirstOrThrowArgs} args - Arguments to find a Item
   * @example
   * // Get one Item
   * const item = await prisma.item.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends itemFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, itemFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__itemClient<runtime.Types.Result.GetResult<Prisma.$itemPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Items that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {itemFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Items
   * const items = await prisma.item.findMany()
   * 
   * // Get first 10 Items
   * const items = await prisma.item.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const itemWithIdOnly = await prisma.item.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends itemFindManyArgs>(args?: Prisma.SelectSubset<T, itemFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$itemPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Item.
   * @param {itemCreateArgs} args - Arguments to create a Item.
   * @example
   * // Create one Item
   * const Item = await prisma.item.create({
   *   data: {
   *     // ... data to create a Item
   *   }
   * })
   * 
   */
  create<T extends itemCreateArgs>(args: Prisma.SelectSubset<T, itemCreateArgs<ExtArgs>>): Prisma.Prisma__itemClient<runtime.Types.Result.GetResult<Prisma.$itemPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Items.
   * @param {itemCreateManyArgs} args - Arguments to create many Items.
   * @example
   * // Create many Items
   * const item = await prisma.item.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends itemCreateManyArgs>(args?: Prisma.SelectSubset<T, itemCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Items and returns the data saved in the database.
   * @param {itemCreateManyAndReturnArgs} args - Arguments to create many Items.
   * @example
   * // Create many Items
   * const item = await prisma.item.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Items and only return the `id`
   * const itemWithIdOnly = await prisma.item.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends itemCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, itemCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$itemPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Item.
   * @param {itemDeleteArgs} args - Arguments to delete one Item.
   * @example
   * // Delete one Item
   * const Item = await prisma.item.delete({
   *   where: {
   *     // ... filter to delete one Item
   *   }
   * })
   * 
   */
  delete<T extends itemDeleteArgs>(args: Prisma.SelectSubset<T, itemDeleteArgs<ExtArgs>>): Prisma.Prisma__itemClient<runtime.Types.Result.GetResult<Prisma.$itemPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Item.
   * @param {itemUpdateArgs} args - Arguments to update one Item.
   * @example
   * // Update one Item
   * const item = await prisma.item.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends itemUpdateArgs>(args: Prisma.SelectSubset<T, itemUpdateArgs<ExtArgs>>): Prisma.Prisma__itemClient<runtime.Types.Result.GetResult<Prisma.$itemPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Items.
   * @param {itemDeleteManyArgs} args - Arguments to filter Items to delete.
   * @example
   * // Delete a few Items
   * const { count } = await prisma.item.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends itemDeleteManyArgs>(args?: Prisma.SelectSubset<T, itemDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Items.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {itemUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Items
   * const item = await prisma.item.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends itemUpdateManyArgs>(args: Prisma.SelectSubset<T, itemUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Items and returns the data updated in the database.
   * @param {itemUpdateManyAndReturnArgs} args - Arguments to update many Items.
   * @example
   * // Update many Items
   * const item = await prisma.item.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Items and only return the `id`
   * const itemWithIdOnly = await prisma.item.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends itemUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, itemUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$itemPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Item.
   * @param {itemUpsertArgs} args - Arguments to update or create a Item.
   * @example
   * // Update or create a Item
   * const item = await prisma.item.upsert({
   *   create: {
   *     // ... data to create a Item
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Item we want to update
   *   }
   * })
   */
  upsert<T extends itemUpsertArgs>(args: Prisma.SelectSubset<T, itemUpsertArgs<ExtArgs>>): Prisma.Prisma__itemClient<runtime.Types.Result.GetResult<Prisma.$itemPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Items.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {itemCountArgs} args - Arguments to filter Items to count.
   * @example
   * // Count the number of Items
   * const count = await prisma.item.count({
   *   where: {
   *     // ... the filter for the Items we want to count
   *   }
   * })
  **/
  count<T extends itemCountArgs>(
    args?: Prisma.Subset<T, itemCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ItemCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Item.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ItemAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends ItemAggregateArgs>(args: Prisma.Subset<T, ItemAggregateArgs>): Prisma.PrismaPromise<GetItemAggregateType<T>>

  /**
   * Group by Item.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {itemGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends itemGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: itemGroupByArgs['orderBy'] }
      : { orderBy?: itemGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, itemGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetItemGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the item model
 */
readonly fields: itemFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for item.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__itemClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  menu<T extends Prisma.menuDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.menuDefaultArgs<ExtArgs>>): Prisma.Prisma__menuClient<runtime.Types.Result.GetResult<Prisma.$menuPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the item model
 */
export interface itemFieldRefs {
  readonly id: Prisma.FieldRef<"item", 'String'>
  readonly menuId: Prisma.FieldRef<"item", 'String'>
  readonly platfrom: Prisma.FieldRef<"item", 'platfrom'>
  readonly arch: Prisma.FieldRef<"item", 'arch'>
  readonly target: Prisma.FieldRef<"item", 'String'>
  readonly updated_at: Prisma.FieldRef<"item", 'DateTime'>
}
    

// Custom InputTypes
/**
 * item findUnique
 */
export type itemFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the item
   */
  select?: Prisma.itemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the item
   */
  omit?: Prisma.itemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.itemInclude<ExtArgs> | null
  /**
   * Filter, which item to fetch.
   */
  where: Prisma.itemWhereUniqueInput
}

/**
 * item findUniqueOrThrow
 */
export type itemFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the item
   */
  select?: Prisma.itemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the item
   */
  omit?: Prisma.itemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.itemInclude<ExtArgs> | null
  /**
   * Filter, which item to fetch.
   */
  where: Prisma.itemWhereUniqueInput
}

/**
 * item findFirst
 */
export type itemFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the item
   */
  select?: Prisma.itemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the item
   */
  omit?: Prisma.itemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.itemInclude<ExtArgs> | null
  /**
   * Filter, which item to fetch.
   */
  where?: Prisma.itemWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of items to fetch.
   */
  orderBy?: Prisma.itemOrderByWithRelationInput | Prisma.itemOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for items.
   */
  cursor?: Prisma.itemWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` items from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` items.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of items.
   */
  distinct?: Prisma.ItemScalarFieldEnum | Prisma.ItemScalarFieldEnum[]
}

/**
 * item findFirstOrThrow
 */
export type itemFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the item
   */
  select?: Prisma.itemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the item
   */
  omit?: Prisma.itemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.itemInclude<ExtArgs> | null
  /**
   * Filter, which item to fetch.
   */
  where?: Prisma.itemWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of items to fetch.
   */
  orderBy?: Prisma.itemOrderByWithRelationInput | Prisma.itemOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for items.
   */
  cursor?: Prisma.itemWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` items from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` items.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of items.
   */
  distinct?: Prisma.ItemScalarFieldEnum | Prisma.ItemScalarFieldEnum[]
}

/**
 * item findMany
 */
export type itemFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the item
   */
  select?: Prisma.itemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the item
   */
  omit?: Prisma.itemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.itemInclude<ExtArgs> | null
  /**
   * Filter, which items to fetch.
   */
  where?: Prisma.itemWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of items to fetch.
   */
  orderBy?: Prisma.itemOrderByWithRelationInput | Prisma.itemOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing items.
   */
  cursor?: Prisma.itemWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` items from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` items.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of items.
   */
  distinct?: Prisma.ItemScalarFieldEnum | Prisma.ItemScalarFieldEnum[]
}

/**
 * item create
 */
export type itemCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the item
   */
  select?: Prisma.itemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the item
   */
  omit?: Prisma.itemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.itemInclude<ExtArgs> | null
  /**
   * The data needed to create a item.
   */
  data: Prisma.XOR<Prisma.itemCreateInput, Prisma.itemUncheckedCreateInput>
}

/**
 * item createMany
 */
export type itemCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many items.
   */
  data: Prisma.itemCreateManyInput | Prisma.itemCreateManyInput[]
}

/**
 * item createManyAndReturn
 */
export type itemCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the item
   */
  select?: Prisma.itemSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the item
   */
  omit?: Prisma.itemOmit<ExtArgs> | null
  /**
   * The data used to create many items.
   */
  data: Prisma.itemCreateManyInput | Prisma.itemCreateManyInput[]
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.itemIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * item update
 */
export type itemUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the item
   */
  select?: Prisma.itemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the item
   */
  omit?: Prisma.itemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.itemInclude<ExtArgs> | null
  /**
   * The data needed to update a item.
   */
  data: Prisma.XOR<Prisma.itemUpdateInput, Prisma.itemUncheckedUpdateInput>
  /**
   * Choose, which item to update.
   */
  where: Prisma.itemWhereUniqueInput
}

/**
 * item updateMany
 */
export type itemUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update items.
   */
  data: Prisma.XOR<Prisma.itemUpdateManyMutationInput, Prisma.itemUncheckedUpdateManyInput>
  /**
   * Filter which items to update
   */
  where?: Prisma.itemWhereInput
  /**
   * Limit how many items to update.
   */
  limit?: number
}

/**
 * item updateManyAndReturn
 */
export type itemUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the item
   */
  select?: Prisma.itemSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the item
   */
  omit?: Prisma.itemOmit<ExtArgs> | null
  /**
   * The data used to update items.
   */
  data: Prisma.XOR<Prisma.itemUpdateManyMutationInput, Prisma.itemUncheckedUpdateManyInput>
  /**
   * Filter which items to update
   */
  where?: Prisma.itemWhereInput
  /**
   * Limit how many items to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.itemIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * item upsert
 */
export type itemUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the item
   */
  select?: Prisma.itemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the item
   */
  omit?: Prisma.itemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.itemInclude<ExtArgs> | null
  /**
   * The filter to search for the item to update in case it exists.
   */
  where: Prisma.itemWhereUniqueInput
  /**
   * In case the item found by the `where` argument doesn't exist, create a new item with this data.
   */
  create: Prisma.XOR<Prisma.itemCreateInput, Prisma.itemUncheckedCreateInput>
  /**
   * In case the item was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.itemUpdateInput, Prisma.itemUncheckedUpdateInput>
}

/**
 * item delete
 */
export type itemDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the item
   */
  select?: Prisma.itemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the item
   */
  omit?: Prisma.itemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.itemInclude<ExtArgs> | null
  /**
   * Filter which item to delete.
   */
  where: Prisma.itemWhereUniqueInput
}

/**
 * item deleteMany
 */
export type itemDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which items to delete
   */
  where?: Prisma.itemWhereInput
  /**
   * Limit how many items to delete.
   */
  limit?: number
}

/**
 * item without action
 */
export type itemDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the item
   */
  select?: Prisma.itemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the item
   */
  omit?: Prisma.itemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.itemInclude<ExtArgs> | null
}
