
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `source` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model source
 * 
 */
export type sourceModel = runtime.Types.Result.DefaultSelection<Prisma.$sourcePayload>

export type AggregateSource = {
  _count: SourceCountAggregateOutputType | null
  _min: SourceMinAggregateOutputType | null
  _max: SourceMaxAggregateOutputType | null
}

export type SourceMinAggregateOutputType = {
  id: string | null
  menuId: string | null
  type: $Enums.source_type | null
  uri: string | null
}

export type SourceMaxAggregateOutputType = {
  id: string | null
  menuId: string | null
  type: $Enums.source_type | null
  uri: string | null
}

export type SourceCountAggregateOutputType = {
  id: number
  menuId: number
  type: number
  uri: number
  _all: number
}


export type SourceMinAggregateInputType = {
  id?: true
  menuId?: true
  type?: true
  uri?: true
}

export type SourceMaxAggregateInputType = {
  id?: true
  menuId?: true
  type?: true
  uri?: true
}

export type SourceCountAggregateInputType = {
  id?: true
  menuId?: true
  type?: true
  uri?: true
  _all?: true
}

export type SourceAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which source to aggregate.
   */
  where?: Prisma.sourceWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of sources to fetch.
   */
  orderBy?: Prisma.sourceOrderByWithRelationInput | Prisma.sourceOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.sourceWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` sources from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` sources.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned sources
  **/
  _count?: true | SourceCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: SourceMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: SourceMaxAggregateInputType
}

export type GetSourceAggregateType<T extends SourceAggregateArgs> = {
      [P in keyof T & keyof AggregateSource]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateSource[P]>
    : Prisma.GetScalarType<T[P], AggregateSource[P]>
}




export type sourceGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.sourceWhereInput
  orderBy?: Prisma.sourceOrderByWithAggregationInput | Prisma.sourceOrderByWithAggregationInput[]
  by: Prisma.SourceScalarFieldEnum[] | Prisma.SourceScalarFieldEnum
  having?: Prisma.sourceScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: SourceCountAggregateInputType | true
  _min?: SourceMinAggregateInputType
  _max?: SourceMaxAggregateInputType
}

export type SourceGroupByOutputType = {
  id: string
  menuId: string
  type: $Enums.source_type
  uri: string
  _count: SourceCountAggregateOutputType | null
  _min: SourceMinAggregateOutputType | null
  _max: SourceMaxAggregateOutputType | null
}

export type GetSourceGroupByPayload<T extends sourceGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<SourceGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof SourceGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], SourceGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], SourceGroupByOutputType[P]>
      }
    >
  >



export type sourceWhereInput = {
  AND?: Prisma.sourceWhereInput | Prisma.sourceWhereInput[]
  OR?: Prisma.sourceWhereInput[]
  NOT?: Prisma.sourceWhereInput | Prisma.sourceWhereInput[]
  id?: Prisma.StringFilter<"source"> | string
  menuId?: Prisma.StringFilter<"source"> | string
  type?: Prisma.Enumsource_typeFilter<"source"> | $Enums.source_type
  uri?: Prisma.StringFilter<"source"> | string
}

export type sourceOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  menuId?: Prisma.SortOrder
  type?: Prisma.SortOrder
  uri?: Prisma.SortOrder
}

export type sourceWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.sourceWhereInput | Prisma.sourceWhereInput[]
  OR?: Prisma.sourceWhereInput[]
  NOT?: Prisma.sourceWhereInput | Prisma.sourceWhereInput[]
  menuId?: Prisma.StringFilter<"source"> | string
  type?: Prisma.Enumsource_typeFilter<"source"> | $Enums.source_type
  uri?: Prisma.StringFilter<"source"> | string
}, "id">

export type sourceOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  menuId?: Prisma.SortOrder
  type?: Prisma.SortOrder
  uri?: Prisma.SortOrder
  _count?: Prisma.sourceCountOrderByAggregateInput
  _max?: Prisma.sourceMaxOrderByAggregateInput
  _min?: Prisma.sourceMinOrderByAggregateInput
}

export type sourceScalarWhereWithAggregatesInput = {
  AND?: Prisma.sourceScalarWhereWithAggregatesInput | Prisma.sourceScalarWhereWithAggregatesInput[]
  OR?: Prisma.sourceScalarWhereWithAggregatesInput[]
  NOT?: Prisma.sourceScalarWhereWithAggregatesInput | Prisma.sourceScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"source"> | string
  menuId?: Prisma.StringWithAggregatesFilter<"source"> | string
  type?: Prisma.Enumsource_typeWithAggregatesFilter<"source"> | $Enums.source_type
  uri?: Prisma.StringWithAggregatesFilter<"source"> | string
}

export type sourceCreateInput = {
  id?: string
  menuId: string
  type: $Enums.source_type
  uri: string
}

export type sourceUncheckedCreateInput = {
  id?: string
  menuId: string
  type: $Enums.source_type
  uri: string
}

export type sourceUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  menuId?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.Enumsource_typeFieldUpdateOperationsInput | $Enums.source_type
  uri?: Prisma.StringFieldUpdateOperationsInput | string
}

export type sourceUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  menuId?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.Enumsource_typeFieldUpdateOperationsInput | $Enums.source_type
  uri?: Prisma.StringFieldUpdateOperationsInput | string
}

export type sourceCreateManyInput = {
  id?: string
  menuId: string
  type: $Enums.source_type
  uri: string
}

export type sourceUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  menuId?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.Enumsource_typeFieldUpdateOperationsInput | $Enums.source_type
  uri?: Prisma.StringFieldUpdateOperationsInput | string
}

export type sourceUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  menuId?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.Enumsource_typeFieldUpdateOperationsInput | $Enums.source_type
  uri?: Prisma.StringFieldUpdateOperationsInput | string
}

export type sourceCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  menuId?: Prisma.SortOrder
  type?: Prisma.SortOrder
  uri?: Prisma.SortOrder
}

export type sourceMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  menuId?: Prisma.SortOrder
  type?: Prisma.SortOrder
  uri?: Prisma.SortOrder
}

export type sourceMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  menuId?: Prisma.SortOrder
  type?: Prisma.SortOrder
  uri?: Prisma.SortOrder
}

export type Enumsource_typeFieldUpdateOperationsInput = {
  set?: $Enums.source_type
}



export type sourceSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  menuId?: boolean
  type?: boolean
  uri?: boolean
}, ExtArgs["result"]["source"]>

export type sourceSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  menuId?: boolean
  type?: boolean
  uri?: boolean
}, ExtArgs["result"]["source"]>

export type sourceSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  menuId?: boolean
  type?: boolean
  uri?: boolean
}, ExtArgs["result"]["source"]>

export type sourceSelectScalar = {
  id?: boolean
  menuId?: boolean
  type?: boolean
  uri?: boolean
}

export type sourceOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "menuId" | "type" | "uri", ExtArgs["result"]["source"]>

export type $sourcePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "source"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    menuId: string
    type: $Enums.source_type
    uri: string
  }, ExtArgs["result"]["source"]>
  composites: {}
}

export type sourceGetPayload<S extends boolean | null | undefined | sourceDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$sourcePayload, S>

export type sourceCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<sourceFindManyArgs, 'select' | 'include' | 'distinct' | 'omit' | 'relationLoadStrategy'> & {
    select?: SourceCountAggregateInputType | true
  }

export interface sourceDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['source'], meta: { name: 'source' } }
  /**
   * Find zero or one Source that matches the filter.
   * @param {sourceFindUniqueArgs} args - Arguments to find a Source
   * @example
   * // Get one Source
   * const source = await prisma.source.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends sourceFindUniqueArgs>(args: Prisma.SelectSubset<T, sourceFindUniqueArgs<ExtArgs>>): Prisma.Prisma__sourceClient<runtime.Types.Result.GetResult<Prisma.$sourcePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Source that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {sourceFindUniqueOrThrowArgs} args - Arguments to find a Source
   * @example
   * // Get one Source
   * const source = await prisma.source.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends sourceFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, sourceFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__sourceClient<runtime.Types.Result.GetResult<Prisma.$sourcePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Source that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {sourceFindFirstArgs} args - Arguments to find a Source
   * @example
   * // Get one Source
   * const source = await prisma.source.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends sourceFindFirstArgs>(args?: Prisma.SelectSubset<T, sourceFindFirstArgs<ExtArgs>>): Prisma.Prisma__sourceClient<runtime.Types.Result.GetResult<Prisma.$sourcePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Source that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {sourceFindFirstOrThrowArgs} args - Arguments to find a Source
   * @example
   * // Get one Source
   * const source = await prisma.source.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends sourceFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, sourceFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__sourceClient<runtime.Types.Result.GetResult<Prisma.$sourcePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Sources that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {sourceFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Sources
   * const sources = await prisma.source.findMany()
   * 
   * // Get first 10 Sources
   * const sources = await prisma.source.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const sourceWithIdOnly = await prisma.source.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends sourceFindManyArgs>(args?: Prisma.SelectSubset<T, sourceFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$sourcePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Source.
   * @param {sourceCreateArgs} args - Arguments to create a Source.
   * @example
   * // Create one Source
   * const Source = await prisma.source.create({
   *   data: {
   *     // ... data to create a Source
   *   }
   * })
   * 
   */
  create<T extends sourceCreateArgs>(args: Prisma.SelectSubset<T, sourceCreateArgs<ExtArgs>>): Prisma.Prisma__sourceClient<runtime.Types.Result.GetResult<Prisma.$sourcePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Sources.
   * @param {sourceCreateManyArgs} args - Arguments to create many Sources.
   * @example
   * // Create many Sources
   * const source = await prisma.source.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends sourceCreateManyArgs>(args?: Prisma.SelectSubset<T, sourceCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Sources and returns the data saved in the database.
   * @param {sourceCreateManyAndReturnArgs} args - Arguments to create many Sources.
   * @example
   * // Create many Sources
   * const source = await prisma.source.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Sources and only return the `id`
   * const sourceWithIdOnly = await prisma.source.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends sourceCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, sourceCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$sourcePayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Source.
   * @param {sourceDeleteArgs} args - Arguments to delete one Source.
   * @example
   * // Delete one Source
   * const Source = await prisma.source.delete({
   *   where: {
   *     // ... filter to delete one Source
   *   }
   * })
   * 
   */
  delete<T extends sourceDeleteArgs>(args: Prisma.SelectSubset<T, sourceDeleteArgs<ExtArgs>>): Prisma.Prisma__sourceClient<runtime.Types.Result.GetResult<Prisma.$sourcePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Source.
   * @param {sourceUpdateArgs} args - Arguments to update one Source.
   * @example
   * // Update one Source
   * const source = await prisma.source.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends sourceUpdateArgs>(args: Prisma.SelectSubset<T, sourceUpdateArgs<ExtArgs>>): Prisma.Prisma__sourceClient<runtime.Types.Result.GetResult<Prisma.$sourcePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Sources.
   * @param {sourceDeleteManyArgs} args - Arguments to filter Sources to delete.
   * @example
   * // Delete a few Sources
   * const { count } = await prisma.source.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends sourceDeleteManyArgs>(args?: Prisma.SelectSubset<T, sourceDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Sources.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {sourceUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Sources
   * const source = await prisma.source.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends sourceUpdateManyArgs>(args: Prisma.SelectSubset<T, sourceUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Sources and returns the data updated in the database.
   * @param {sourceUpdateManyAndReturnArgs} args - Arguments to update many Sources.
   * @example
   * // Update many Sources
   * const source = await prisma.source.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Sources and only return the `id`
   * const sourceWithIdOnly = await prisma.source.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends sourceUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, sourceUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$sourcePayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Source.
   * @param {sourceUpsertArgs} args - Arguments to update or create a Source.
   * @example
   * // Update or create a Source
   * const source = await prisma.source.upsert({
   *   create: {
   *     // ... data to create a Source
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Source we want to update
   *   }
   * })
   */
  upsert<T extends sourceUpsertArgs>(args: Prisma.SelectSubset<T, sourceUpsertArgs<ExtArgs>>): Prisma.Prisma__sourceClient<runtime.Types.Result.GetResult<Prisma.$sourcePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Sources.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {sourceCountArgs} args - Arguments to filter Sources to count.
   * @example
   * // Count the number of Sources
   * const count = await prisma.source.count({
   *   where: {
   *     // ... the filter for the Sources we want to count
   *   }
   * })
  **/
  count<T extends sourceCountArgs>(
    args?: Prisma.Subset<T, sourceCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], SourceCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Source.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SourceAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends SourceAggregateArgs>(args: Prisma.Subset<T, SourceAggregateArgs>): Prisma.PrismaPromise<GetSourceAggregateType<T>>

  /**
   * Group by Source.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {sourceGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends sourceGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: sourceGroupByArgs['orderBy'] }
      : { orderBy?: sourceGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, sourceGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetSourceGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the source model
 */
readonly fields: sourceFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for source.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__sourceClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the source model
 */
export interface sourceFieldRefs {
  readonly id: Prisma.FieldRef<"source", 'String'>
  readonly menuId: Prisma.FieldRef<"source", 'String'>
  readonly type: Prisma.FieldRef<"source", 'source_type'>
  readonly uri: Prisma.FieldRef<"source", 'String'>
}
    

// Custom InputTypes
/**
 * source findUnique
 */
export type sourceFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the source
   */
  select?: Prisma.sourceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the source
   */
  omit?: Prisma.sourceOmit<ExtArgs> | null
  /**
   * Filter, which source to fetch.
   */
  where: Prisma.sourceWhereUniqueInput
}

/**
 * source findUniqueOrThrow
 */
export type sourceFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the source
   */
  select?: Prisma.sourceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the source
   */
  omit?: Prisma.sourceOmit<ExtArgs> | null
  /**
   * Filter, which source to fetch.
   */
  where: Prisma.sourceWhereUniqueInput
}

/**
 * source findFirst
 */
export type sourceFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the source
   */
  select?: Prisma.sourceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the source
   */
  omit?: Prisma.sourceOmit<ExtArgs> | null
  /**
   * Filter, which source to fetch.
   */
  where?: Prisma.sourceWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of sources to fetch.
   */
  orderBy?: Prisma.sourceOrderByWithRelationInput | Prisma.sourceOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for sources.
   */
  cursor?: Prisma.sourceWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` sources from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` sources.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of sources.
   */
  distinct?: Prisma.SourceScalarFieldEnum | Prisma.SourceScalarFieldEnum[]
}

/**
 * source findFirstOrThrow
 */
export type sourceFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the source
   */
  select?: Prisma.sourceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the source
   */
  omit?: Prisma.sourceOmit<ExtArgs> | null
  /**
   * Filter, which source to fetch.
   */
  where?: Prisma.sourceWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of sources to fetch.
   */
  orderBy?: Prisma.sourceOrderByWithRelationInput | Prisma.sourceOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for sources.
   */
  cursor?: Prisma.sourceWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` sources from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` sources.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of sources.
   */
  distinct?: Prisma.SourceScalarFieldEnum | Prisma.SourceScalarFieldEnum[]
}

/**
 * source findMany
 */
export type sourceFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the source
   */
  select?: Prisma.sourceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the source
   */
  omit?: Prisma.sourceOmit<ExtArgs> | null
  /**
   * Filter, which sources to fetch.
   */
  where?: Prisma.sourceWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of sources to fetch.
   */
  orderBy?: Prisma.sourceOrderByWithRelationInput | Prisma.sourceOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing sources.
   */
  cursor?: Prisma.sourceWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` sources from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` sources.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of sources.
   */
  distinct?: Prisma.SourceScalarFieldEnum | Prisma.SourceScalarFieldEnum[]
}

/**
 * source create
 */
export type sourceCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the source
   */
  select?: Prisma.sourceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the source
   */
  omit?: Prisma.sourceOmit<ExtArgs> | null
  /**
   * The data needed to create a source.
   */
  data: Prisma.XOR<Prisma.sourceCreateInput, Prisma.sourceUncheckedCreateInput>
}

/**
 * source createMany
 */
export type sourceCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many sources.
   */
  data: Prisma.sourceCreateManyInput | Prisma.sourceCreateManyInput[]
}

/**
 * source createManyAndReturn
 */
export type sourceCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the source
   */
  select?: Prisma.sourceSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the source
   */
  omit?: Prisma.sourceOmit<ExtArgs> | null
  /**
   * The data used to create many sources.
   */
  data: Prisma.sourceCreateManyInput | Prisma.sourceCreateManyInput[]
}

/**
 * source update
 */
export type sourceUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the source
   */
  select?: Prisma.sourceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the source
   */
  omit?: Prisma.sourceOmit<ExtArgs> | null
  /**
   * The data needed to update a source.
   */
  data: Prisma.XOR<Prisma.sourceUpdateInput, Prisma.sourceUncheckedUpdateInput>
  /**
   * Choose, which source to update.
   */
  where: Prisma.sourceWhereUniqueInput
}

/**
 * source updateMany
 */
export type sourceUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update sources.
   */
  data: Prisma.XOR<Prisma.sourceUpdateManyMutationInput, Prisma.sourceUncheckedUpdateManyInput>
  /**
   * Filter which sources to update
   */
  where?: Prisma.sourceWhereInput
  /**
   * Limit how many sources to update.
   */
  limit?: number
}

/**
 * source updateManyAndReturn
 */
export type sourceUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the source
   */
  select?: Prisma.sourceSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the source
   */
  omit?: Prisma.sourceOmit<ExtArgs> | null
  /**
   * The data used to update sources.
   */
  data: Prisma.XOR<Prisma.sourceUpdateManyMutationInput, Prisma.sourceUncheckedUpdateManyInput>
  /**
   * Filter which sources to update
   */
  where?: Prisma.sourceWhereInput
  /**
   * Limit how many sources to update.
   */
  limit?: number
}

/**
 * source upsert
 */
export type sourceUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the source
   */
  select?: Prisma.sourceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the source
   */
  omit?: Prisma.sourceOmit<ExtArgs> | null
  /**
   * The filter to search for the source to update in case it exists.
   */
  where: Prisma.sourceWhereUniqueInput
  /**
   * In case the source found by the `where` argument doesn't exist, create a new source with this data.
   */
  create: Prisma.XOR<Prisma.sourceCreateInput, Prisma.sourceUncheckedCreateInput>
  /**
   * In case the source was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.sourceUpdateInput, Prisma.sourceUncheckedUpdateInput>
}

/**
 * source delete
 */
export type sourceDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the source
   */
  select?: Prisma.sourceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the source
   */
  omit?: Prisma.sourceOmit<ExtArgs> | null
  /**
   * Filter which source to delete.
   */
  where: Prisma.sourceWhereUniqueInput
}

/**
 * source deleteMany
 */
export type sourceDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which sources to delete
   */
  where?: Prisma.sourceWhereInput
  /**
   * Limit how many sources to delete.
   */
  limit?: number
}

/**
 * source without action
 */
export type sourceDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the source
   */
  select?: Prisma.sourceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the source
   */
  omit?: Prisma.sourceOmit<ExtArgs> | null
}
