
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports various common sort, input & filter types that are not directly linked to a particular model.
 *
 * 🟢 You can import this file directly.
 */

import type * as runtime from "@prisma/client/runtime/client"
import * as $Enums from "./enums"
import type * as Prisma from "./internal/prismaNamespace"


export type StringFilter<$PrismaModel = never> = {
  equals?: string | Prisma.StringFieldRefInput<$PrismaModel>
  in?: string[]
  notIn?: string[]
  lt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  lte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  contains?: string | Prisma.StringFieldRefInput<$PrismaModel>
  startsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  endsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  not?: Prisma.NestedStringFilter<$PrismaModel> | string
}

export type StringWithAggregatesFilter<$PrismaModel = never> = {
  equals?: string | Prisma.StringFieldRefInput<$PrismaModel>
  in?: string[]
  notIn?: string[]
  lt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  lte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  contains?: string | Prisma.StringFieldRefInput<$PrismaModel>
  startsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  endsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  not?: Prisma.NestedStringWithAggregatesFilter<$PrismaModel> | string
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedStringFilter<$PrismaModel>
  _max?: Prisma.NestedStringFilter<$PrismaModel>
}

export type EnumplatfromFilter<$PrismaModel = never> = {
  equals?: $Enums.platfrom | Prisma.EnumplatfromFieldRefInput<$PrismaModel>
  in?: $Enums.platfrom[]
  notIn?: $Enums.platfrom[]
  not?: Prisma.NestedEnumplatfromFilter<$PrismaModel> | $Enums.platfrom
}

export type EnumarchFilter<$PrismaModel = never> = {
  equals?: $Enums.arch | Prisma.EnumarchFieldRefInput<$PrismaModel>
  in?: $Enums.arch[]
  notIn?: $Enums.arch[]
  not?: Prisma.NestedEnumarchFilter<$PrismaModel> | $Enums.arch
}

export type DateTimeFilter<$PrismaModel = never> = {
  equals?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  in?: Date[] | string[]
  notIn?: Date[] | string[]
  lt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  lte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedDateTimeFilter<$PrismaModel> | Date | string
}

export type EnumplatfromWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.platfrom | Prisma.EnumplatfromFieldRefInput<$PrismaModel>
  in?: $Enums.platfrom[]
  notIn?: $Enums.platfrom[]
  not?: Prisma.NestedEnumplatfromWithAggregatesFilter<$PrismaModel> | $Enums.platfrom
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumplatfromFilter<$PrismaModel>
  _max?: Prisma.NestedEnumplatfromFilter<$PrismaModel>
}

export type EnumarchWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.arch | Prisma.EnumarchFieldRefInput<$PrismaModel>
  in?: $Enums.arch[]
  notIn?: $Enums.arch[]
  not?: Prisma.NestedEnumarchWithAggregatesFilter<$PrismaModel> | $Enums.arch
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumarchFilter<$PrismaModel>
  _max?: Prisma.NestedEnumarchFilter<$PrismaModel>
}

export type DateTimeWithAggregatesFilter<$PrismaModel = never> = {
  equals?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  in?: Date[] | string[]
  notIn?: Date[] | string[]
  lt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  lte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedDateTimeWithAggregatesFilter<$PrismaModel> | Date | string
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedDateTimeFilter<$PrismaModel>
  _max?: Prisma.NestedDateTimeFilter<$PrismaModel>
}

export type Enumsource_typeFilter<$PrismaModel = never> = {
  equals?: $Enums.source_type | Prisma.Enumsource_typeFieldRefInput<$PrismaModel>
  in?: $Enums.source_type[]
  notIn?: $Enums.source_type[]
  not?: Prisma.NestedEnumsource_typeFilter<$PrismaModel> | $Enums.source_type
}

export type Enumsource_typeWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.source_type | Prisma.Enumsource_typeFieldRefInput<$PrismaModel>
  in?: $Enums.source_type[]
  notIn?: $Enums.source_type[]
  not?: Prisma.NestedEnumsource_typeWithAggregatesFilter<$PrismaModel> | $Enums.source_type
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumsource_typeFilter<$PrismaModel>
  _max?: Prisma.NestedEnumsource_typeFilter<$PrismaModel>
}

export type NestedStringFilter<$PrismaModel = never> = {
  equals?: string | Prisma.StringFieldRefInput<$PrismaModel>
  in?: string[]
  notIn?: string[]
  lt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  lte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  contains?: string | Prisma.StringFieldRefInput<$PrismaModel>
  startsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  endsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  not?: Prisma.NestedStringFilter<$PrismaModel> | string
}

export type NestedStringWithAggregatesFilter<$PrismaModel = never> = {
  equals?: string | Prisma.StringFieldRefInput<$PrismaModel>
  in?: string[]
  notIn?: string[]
  lt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  lte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  contains?: string | Prisma.StringFieldRefInput<$PrismaModel>
  startsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  endsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  not?: Prisma.NestedStringWithAggregatesFilter<$PrismaModel> | string
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedStringFilter<$PrismaModel>
  _max?: Prisma.NestedStringFilter<$PrismaModel>
}

export type NestedIntFilter<$PrismaModel = never> = {
  equals?: number | Prisma.IntFieldRefInput<$PrismaModel>
  in?: number[]
  notIn?: number[]
  lt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  lte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  not?: Prisma.NestedIntFilter<$PrismaModel> | number
}

export type NestedEnumplatfromFilter<$PrismaModel = never> = {
  equals?: $Enums.platfrom | Prisma.EnumplatfromFieldRefInput<$PrismaModel>
  in?: $Enums.platfrom[]
  notIn?: $Enums.platfrom[]
  not?: Prisma.NestedEnumplatfromFilter<$PrismaModel> | $Enums.platfrom
}

export type NestedEnumarchFilter<$PrismaModel = never> = {
  equals?: $Enums.arch | Prisma.EnumarchFieldRefInput<$PrismaModel>
  in?: $Enums.arch[]
  notIn?: $Enums.arch[]
  not?: Prisma.NestedEnumarchFilter<$PrismaModel> | $Enums.arch
}

export type NestedDateTimeFilter<$PrismaModel = never> = {
  equals?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  in?: Date[] | string[]
  notIn?: Date[] | string[]
  lt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  lte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedDateTimeFilter<$PrismaModel> | Date | string
}

export type NestedEnumplatfromWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.platfrom | Prisma.EnumplatfromFieldRefInput<$PrismaModel>
  in?: $Enums.platfrom[]
  notIn?: $Enums.platfrom[]
  not?: Prisma.NestedEnumplatfromWithAggregatesFilter<$PrismaModel> | $Enums.platfrom
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumplatfromFilter<$PrismaModel>
  _max?: Prisma.NestedEnumplatfromFilter<$PrismaModel>
}

export type NestedEnumarchWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.arch | Prisma.EnumarchFieldRefInput<$PrismaModel>
  in?: $Enums.arch[]
  notIn?: $Enums.arch[]
  not?: Prisma.NestedEnumarchWithAggregatesFilter<$PrismaModel> | $Enums.arch
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumarchFilter<$PrismaModel>
  _max?: Prisma.NestedEnumarchFilter<$PrismaModel>
}

export type NestedDateTimeWithAggregatesFilter<$PrismaModel = never> = {
  equals?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  in?: Date[] | string[]
  notIn?: Date[] | string[]
  lt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  lte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedDateTimeWithAggregatesFilter<$PrismaModel> | Date | string
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedDateTimeFilter<$PrismaModel>
  _max?: Prisma.NestedDateTimeFilter<$PrismaModel>
}

export type NestedEnumsource_typeFilter<$PrismaModel = never> = {
  equals?: $Enums.source_type | Prisma.Enumsource_typeFieldRefInput<$PrismaModel>
  in?: $Enums.source_type[]
  notIn?: $Enums.source_type[]
  not?: Prisma.NestedEnumsource_typeFilter<$PrismaModel> | $Enums.source_type
}

export type NestedEnumsource_typeWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.source_type | Prisma.Enumsource_typeFieldRefInput<$PrismaModel>
  in?: $Enums.source_type[]
  notIn?: $Enums.source_type[]
  not?: Prisma.NestedEnumsource_typeWithAggregatesFilter<$PrismaModel> | $Enums.source_type
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumsource_typeFilter<$PrismaModel>
  _max?: Prisma.NestedEnumsource_typeFilter<$PrismaModel>
}


