
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
* This file exports all enum related types from the schema.
*
* 🟢 You can import this file directly.
*/

export const platfrom = {
  ANY: 'ANY',
  WINDOES: 'WINDOES',
  LINUX: 'LINUX',
  MACOS: 'MACOS',
  ANDROID: 'ANDROID',
  IOS: 'IOS'
} as const

export type platfrom = (typeof platfrom)[keyof typeof platfrom]


export const arch = {
  ANY: 'ANY',
  X86_64: 'X86_64',
  AARCH64: 'AARCH64',
  AARCH32: 'AARCH32'
} as const

export type arch = (typeof arch)[keyof typeof arch]


export const source_type = {
  GITHUB: 'GITHUB'
} as const

export type source_type = (typeof source_type)[keyof typeof source_type]
